packages:
  - packages/*
  - services/*

catalog:
  "@types/node": 22.14.0
  axios: 1.7.9
  camelcase-keys: 9.1.3
  change-case: 5.4.4
  neverthrow: 8.2.0
  tsx: 4.19.3
  typescript: 5.7.3
  uuid: 11.1.0
  zod: 3.24.3

catalogs:
  api:
    "@fastify/cors": 11.0.1
    "@fastify/formbody": 8.0.1
    "@fastify/multipart": 9.0.3
    "@sinclair/typebox": 0.34.33
    fastify: 5.2.2
    http-status-codes: 2.3.0

  auth:
    "@types/bcryptjs": 3.0.0
    "@types/jsonwebtoken": 9.0.9
    bcryptjs: 3.0.2
    jsonwebtoken: 9.0.2

  knex:
    knex-stringcase: 1.5.5
    knex: 3.1.0
    pg: 8.14.1

  pino:
    pino-pretty: 13.0.0
    pino: 9.6.0
