name: auth-example

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    depends_on:
      keycloak_db:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: >
      start-dev
      --http-port=8080
      --hostname=http://localhost:8080

  keycloak_db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"
    volumes:
      - db_auth_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d keycloak"]
      interval: 5s
      timeout: 5s
      retries: 10

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_example
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d auth_example"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_auth_data:
  db_data:
